### ISSUE TITLE
Unable to add new face models

### ISSUE THREAD

**Issue by lluisfranco** [slimbook/slimbookface#1]

**Comment by lluisfranco** [comment]
Hi there,
I've installed the last version of slimbook face (1.4.4) but I'm unable to add a new face model.
When I try to add a new model (click on button) a dialog appears:

![image](https://user-images.githubusercontent.com/6582934/124167403-47430b80-daa4-11eb-80b7-2e36867e0fa4.png)

I can add a name but when clicking the show webcam button nothing happens (just a lag of 5-10 sec).
I've tried to reinstall the webcam software twice with identical results :S
Note: When I reinstall howdy for first time it doesn't detect my webcam:

![image](https://user-images.githubusercontent.com/6582934/124168211-1f07dc80-daa5-11eb-8629-7d4b9f784cd7.png)

OS: Linux Mint 20.1 Cinnamon (up to date)
Cinnamon: 4.8.6
Kernel: 5.4.0-77-generic

Running on a SLIMBOOK PRO-X
Intel© Core™ i7-10510U CPU @ 1.80GHz × 4
31.2 GiB

**Comment by slimbook** [comment]
Hi Lluis,
Can you show me the app? have you "Devices" or "Dispositivos"?
Thanks

**Comment by lluisfranco** [comment]
Sure! :)

I've 2 different devices:
![image](https://user-images.githubusercontent.com/6582934/124242149-b9573700-db1c-11eb-9ecd-d360490cd440.png)

When I click on a device on the list, a notification message appears:
![image](https://user-images.githubusercontent.com/6582934/124242555-25399f80-db1d-11eb-9e06-25b2307a1e96.png)

**Comment by slimbook** [comment]
Do you see a red led on the webcam when you select a device?
Try adding a face model after selecting a device.

**Comment by lluisfranco** [comment]
Nope. 
There's no red light on cam when selecting any of the two devices :S
The same notification appears when I click the first or the second device.
And FYI during the installation of the driver, only appears the blue light on the second attempt (first I select none, then the light appears).

**Comment by slimbook** [comment]
> But
When a webcam is selected, it is always shown the same notification. That's because we can't detect if your selected webcam is an IR webcam. By the way, can you execute 'slimbookface' on a terminal? It should show the error,  in case the error is something like "/lib/security/howdy/models/'user'.dat" does not exist,  you should reinstall howdy, because that folder is autogenerated by howdy when a face model is added.

**Comment by lluisfranco** [comment]
Well... that's a big surprise.
Launching slimbookface on a terminal allows me to add a new face model :S
However, there are a bunch of error in the terminal, in some phyton modules and then a popup window appears:

![image](https://user-images.githubusercontent.com/6582934/124299639-f4c62580-db5d-11eb-8011-30fa4cd4cc57.png)

This screenshot is not the first time, and I cannot catch the errors, sorry.
Sadly, all these errors only appeared the first time.
Now I cannot reproduce, but it works... at least from the terminal :D 
Here's the terminal code (without all the errors):

```
No face model known for the user lluisfranco
No face model known for the user lluisfranco
0 faces added
/usr/local/bin/howdy
disabled = false
X-Cinnamon
Face clicked
+ python3 /usr/share/slimbookface/slimbookface-howdy.py test none

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

Howdy test

Closing window
+ python3 /usr/share/slimbookface/slimbookface-howdy.py add me
Added a new model to lluisfranco
/usr/local/bin/howdy
disabled = false
X-Cinnamon
```

A lot of thanks! ;)
You did magic,

**Comment by lluisfranco** [comment]
After a reboot I can reproduce the error but only randomly :S
It's not important because finally I added a couple of face modes (with and without glasses) :P
Here is the terminal output:
```

/usr/local/bin/howdy
disabled = false
X-Cinnamon
Face clicked
+ python3 /usr/share/slimbookface/slimbookface-howdy.py test none

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 109, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 66, in <module>
    cv2.setMouseCallback("Howdy Test", mouse)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/highgui/src/window_QT.cpp:717: error: (-27:Null pointer) NULL window handler in function 'cvSetMouseCallback'

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_lib_security_howdy_cli.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 109, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 66, in <module>
    cv2.setMouseCallback("Howdy Test", mouse)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/highgui/src/window_QT.cpp:717: error: (-27:Null pointer) NULL window handler in function 'cvSetMouseCallback'

Howdy test
+ python3 /usr/share/slimbookface/slimbookface-howdy.py test none

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 109, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 66, in <module>
    cv2.setMouseCallback("Howdy Test", mouse)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/highgui/src/window_QT.cpp:717: error: (-27:Null pointer) NULL window handler in function 'cvSetMouseCallback'

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_lib_security_howdy_cli.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 109, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 66, in <module>
    cv2.setMouseCallback("Howdy Test", mouse)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/highgui/src/window_QT.cpp:717: error: (-27:Null pointer) NULL window handler in function 'cvSetMouseCallback'

 Howdy test
```

**Comment by slimbook** [comment]
Solved in new version :)
