### ISSUE TITLE
PPA does not include slimbookface

### ISSUE THREAD

**Issue by ettmetal** [slimbook/slimbookface#5]
Following Install instructions from the readme, there is no slimbookface package available via the added PPA.

```bash
$ sudo add-apt-repository ppa:slimbook/slimbook
$ apt-cache search slimbook    
slimbookamdcontroller - Aplicacion para la gestion de rendimiento de procesadores amd
slimbookbattery - Slimbook Battery
slimbookgestures - Slimbook Gestures
slimbookintelcontroller - Aplicacion para la gestion de rendimiento de procesadores intel
slimbookrgbkeyboard - Slimbook RGB, gestiona el color y brillo de tu teclado.
slimbooksensortouchpad - set your touchpad
slimbookwelcome - Slimbook Welcome
```

No slimbookface is listed. Trying to install fails

```bash
$ sudo apt install slimbookface
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package slimbookface
```

**Comment by ettmetal** [comment]
I just double-checked, and it seems that howdy _is_ available for 21.04 - at least, there is a package for it on boltgolt's Launchpad ppa: https://launchpad.net/~boltgolt/+archive/ubuntu/howdy/+packages. (It seems 21.04 = Hirsute?) Is there something I can do to help?

**Comment by slimbook** [comment]
Yes, that's true, but we tried to install it and and it's not working (in 21.04, in 21.10 seems to work), in any case we are copying packages for those releases so you can try :)

**Comment by ettmetal** [comment]
Interesting, I'm sure I had howdy working on 21.04 🤔. What do I do to try it?

**Comment by slimbook** [comment]
You can use commandline @example; sudo howdy add
